# Generated by Django 5.1.6 on 2025-06-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SubCategories'},
        ),
    ]
